### PR TITLE
Final release and declare unmaintained

### PR DESCRIPTION
**Pull request by tarsius**
I intend to push this commit in a few days and tag it with `2.2.0` unless @llvilanova wishes to move this to his own account. Otherwise I will move this to the [Emacsattic](https://github.com/emacsattic).

### CODE REVIEW

**Comment by llvilanova** [comment]
I still do use this, but was waiting for some future plans in magit to handle patch+mail management to see if magit-stgit is still worth it to me.

**Comment by tarsius** [comment]
> was waiting for some future plans in magit to handle patch+mail management

I don't to implement anything any time soon. Originally I planned to improve support for this, but Forge has taken a different turn.

> I still do use this

Can we move it to your user account then.

I think this should work:

1. I move it to the `emacsorphanage` organisation and give you admin rights for `emacsorphanage/magit-stgit`.
2. You move it from there to your account.

**Comment by tarsius** [comment]
Err, of course I can just give you admin permissions for *this* repository instead. :roll_eyes:

**Comment by tarsius** [comment]
... instead of transferring to `emacsorphanage` first. (I still would like to remove it from this organization, I already maintain enough code that I never use.)

**Comment by tarsius** [comment]
I invited you to become an admin of this repository so that you could transfer it, but I cannot find that invitation anywhere in the Github interface anymore. Did you get it?

**Pull request merged**
